name: Build Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
  push:

env:
  IMAGE_NAME: dpvduncan/deluge:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install jq
      uses: dcarbone/install-jq-action@v2

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: |
          linux/arm32/v6
          linux/arm32/v7
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}
